{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "326854cd-84b0-4251-b50b-a98c7fa862b7",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================================\n",
    "# NOTEBOOKLM-STYLE PATENT ANALYZER\n",
    "# 3-Column Interface: Source | Agent | Visualization\n",
    "# ============================================================================\n",
    "\n",
    "import streamlit as st\n",
    "import fitz\n",
    "import re\n",
    "from pathlib import Path\n",
    "from difflib import SequenceMatcher\n",
    "import base64\n",
    "\n",
    "# Set page config\n",
    "st.set_page_config(\n",
    "    page_title=\"Patent Analyzer\",\n",
    "    page_icon=\"🔍\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "# Folders\n",
    "BASE_FOLDER = Path.cwd().parent\n",
    "PATENTS_FOLDER = BASE_FOLDER / \"Patents\"\n",
    "HIGHLIGHTED_FOLDER = BASE_FOLDER / \"highlighted\"\n",
    "PATENTS_FOLDER.mkdir(exist_ok=True)\n",
    "HIGHLIGHTED_FOLDER.mkdir(exist_ok=True)\n",
    "\n",
    "# ============================================================================\n",
    "# CORE FUNCTIONS\n",
    "# ============================================================================\n",
    "\n",
    "def clean_text(text):\n",
    "    \"\"\"Clean text for matching\"\"\"\n",
    "    text = text.replace('\\n', ' ').replace('\\r', ' ')\n",
    "    text = re.sub(r'\\s+', ' ', text)\n",
    "    return text.strip()\n",
    "\n",
    "def search_pdf(pdf_path, search_items):\n",
    "    \"\"\"Search PDF and return detailed results\"\"\"\n",
    "    \n",
    "    doc = fitz.open(str(pdf_path))\n",
    "    results = {}\n",
    "    \n",
    "    for item in search_items:\n",
    "        results[item] = {\n",
    "            'count': 0,\n",
    "            'pages': [],\n",
    "            'total_chars': len(item),\n",
    "            'found': False\n",
    "        }\n",
    "    \n",
    "    # Search each page\n",
    "    for page_num in range(doc.page_count):\n",
    "        page = doc.load_page(page_num)\n",
    "        page_text = page.get_text(\"text\")\n",
    "        page_text_clean = clean_text(page_text).lower()\n",
    "        \n",
    "        for item in search_items:\n",
    "            item_clean = clean_text(item).lower()\n",
    "            \n",
    "            if item_clean in page_text_clean:\n",
    "                results[item]['found'] = True\n",
    "                count = page_text_clean.count(item_clean)\n",
    "                results[item]['count'] += count\n",
    "                \n",
    "                if page_num + 1 not in results[item]['pages']:\n",
    "                    results[item]['pages'].append(page_num + 1)\n",
    "    \n",
    "    doc.close()\n",
    "    \n",
    "    # Calculate match percentage\n",
    "    total_items = len(search_items)\n",
    "    matched_items = sum(1 for r in results.values() if r['found'])\n",
    "    match_percentage = (matched_items / total_items * 100) if total_items > 0 else 0\n",
    "    \n",
    "    return results, match_percentage\n",
    "\n",
    "def highlight_pdf(pdf_path, output_path, search_items):\n",
    "    \"\"\"Create highlighted PDF\"\"\"\n",
    "    \n",
    "    doc = fitz.open(str(pdf_path))\n",
    "    total_highlights = 0\n",
    "    \n",
    "    for page_num in range(doc.page_count):\n",
    "        page = doc.load_page(page_num)\n",
    "        page_text = page.get_text(\"text\")\n",
    "        page_text_clean = clean_text(page_text).lower()\n",
    "        \n",
    "        for item in search_items:\n",
    "            item_clean = clean_text(item).lower()\n",
    "            \n",
    "            if item_clean not in page_text_clean:\n",
    "                continue\n",
    "            \n",
    "            # Split into words\n",
    "            words = item_clean.split()\n",
    "            \n",
    "            if len(words) == 1:\n",
    "                # Single word\n",
    "                instances = page.search_for(words[0], quads=True)\n",
    "                for inst in instances:\n",
    "                    highlight = page.add_highlight_annot(inst)\n",
    "                    highlight.set_colors(stroke=[1, 0.9, 0])\n",
    "                    highlight.set_opacity(0.35)\n",
    "                    highlight.update()\n",
    "                    total_highlights += 1\n",
    "            else:\n",
    "                # Multiple words - search first word\n",
    "                first_instances = page.search_for(words[0], quads=True)\n",
    "                \n",
    "                for inst in first_instances:\n",
    "                    rect = inst.rect\n",
    "                    char_width = (rect.x1 - rect.x0) / len(words[0])\n",
    "                    estimated_width = char_width * len(item_clean)\n",
    "                    \n",
    "                    expanded = fitz.Rect(\n",
    "                        rect.x0,\n",
    "                        rect.y0 - 2,\n",
    "                        min(rect.x0 + estimated_width * 1.4, page.rect.width),\n",
    "                        rect.y1 + 2\n",
    "                    )\n",
    "                    \n",
    "                    try:\n",
    "                        rect_text = page.get_textbox(expanded)\n",
    "                        rect_clean = clean_text(rect_text).lower()\n",
    "                        \n",
    "                        similarity = SequenceMatcher(None, item_clean, rect_clean).ratio()\n",
    "                        \n",
    "                        if similarity > 0.65:\n",
    "                            highlight = page.add_highlight_annot(expanded)\n",
    "                            highlight.set_colors(stroke=[1, 0.9, 0])\n",
    "                            highlight.set_opacity(0.35)\n",
    "                            highlight.update()\n",
    "                            total_highlights += 1\n",
    "                    except:\n",
    "                        pass\n",
    "    \n",
    "    doc.save(str(output_path))\n",
    "    doc.close()\n",
    "    \n",
    "    return total_highlights\n",
    "\n",
    "def pdf_to_base64(pdf_path):\n",
    "    \"\"\"Convert PDF to base64 for display\"\"\"\n",
    "    with open(pdf_path, \"rb\") as f:\n",
    "        return base64.b64encode(f.read()).decode()\n",
    "\n",
    "# ============================================================================\n",
    "# STREAMLIT UI - 3 COLUMN LAYOUT\n",
    "# ============================================================================\n",
    "\n",
    "# Custom CSS\n",
    "st.markdown(\"\"\"\n",
    "<style>\n",
    "    .main-title {\n",
    "        font-size: 2.5rem;\n",
    "        font-weight: bold;\n",
    "        text-align: center;\n",
    "        color: #1f77b4;\n",
    "        margin-bottom: 2rem;\n",
    "    }\n",
    "    .column-header {\n",
    "        font-size: 1.3rem;\n",
    "        font-weight: bold;\n",
    "        padding: 10px;\n",
    "        background: linear-gradient(90deg, #667eea 0%, #764ba2 100%);\n",
    "        color: white;\n",
    "        border-radius: 5px;\n",
    "        margin-bottom: 1rem;\n",
    "        text-align: center;\n",
    "    }\n",
    "    .metric-box {\n",
    "        background: #f0f2f6;\n",
    "        padding: 15px;\n",
    "        border-radius: 10px;\n",
    "        border-left: 5px solid #1f77b4;\n",
    "        margin: 10px 0;\n",
    "    }\n",
    "    .success-box {\n",
    "        background: #d4edda;\n",
    "        padding: 10px;\n",
    "        border-radius: 5px;\n",
    "        border-left: 4px solid #28a745;\n",
    "        margin: 5px 0;\n",
    "    }\n",
    "    .warning-box {\n",
    "        background: #fff3cd;\n",
    "        padding: 10px;\n",
    "        border-radius: 5px;\n",
    "        border-left: 4px solid #ffc107;\n",
    "        margin: 5px 0;\n",
    "    }\n",
    "</style>\n",
    "\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "# Main Title\n",
    "st.markdown('<div class=\"main-title\">🔍 AI Patent Analyzer</div>', unsafe_allow_html=True)\n",
    "\n",
    "# Initialize session state\n",
    "if 'analyzed' not in st.session_state:\n",
    "    st.session_state.analyzed = False\n",
    "if 'results' not in st.session_state:\n",
    "    st.session_state.results = None\n",
    "if 'highlighted_pdf' not in st.session_state:\n",
    "    st.session_state.highlighted_pdf = None\n",
    "\n",
    "# ============================================================================\n",
    "# 3-COLUMN LAYOUT\n",
    "# ============================================================================\n",
    "\n",
    "col1, col2, col3 = st.columns([1, 1.2, 1.3])\n",
    "\n",
    "# ============================================================================\n",
    "# COLUMN 1: SOURCE PANEL\n",
    "# ============================================================================\n",
    "\n",
    "with col1:\n",
    "    st.markdown('<div class=\"column-header\">📁 SOURCE</div>', unsafe_allow_html=True)\n",
    "    \n",
    "    # List available PDFs\n",
    "    pdf_files = list(PATENTS_FOLDER.glob('*.pdf'))\n",
    "    \n",
    "    if pdf_files:\n",
    "        st.info(f\"📚 {len(pdf_files)} PDF(s) available\")\n",
    "        \n",
    "        # Select PDF\n",
    "        selected_file = st.selectbox(\n",
    "            \"Select PDF to analyze:\",\n",
    "            options=[f.stem for f in pdf_files],\n",
    "            key='pdf_select'\n",
    "        )\n",
    "        \n",
    "        if selected_file:\n",
    "            pdf_path = PATENTS_FOLDER / f\"{selected_file}.pdf\"\n",
    "            \n",
    "            # Show PDF info\n",
    "            doc = fitz.open(str(pdf_path))\n",
    "            st.markdown(f\"\"\"\n",
    "            <div class=\"metric-box\">\n",
    "                <b>📄 File:</b> {selected_file}<br>\n",
    "                <b>📑 Pages:</b> {doc.page_count}<br>\n",
    "                <b>💾 Size:</b> {pdf_path.stat().st_size / 1024:.1f} KB\n",
    "            </div>\n",
    "            \"\"\", unsafe_allow_html=True)\n",
    "            doc.close()\n",
    "    else:\n",
    "        st.warning(f\"No PDFs found in: {PATENTS_FOLDER}\")\n",
    "        st.info(\"💡 Add PDF files to the Patents folder\")\n",
    "    \n",
    "    # Upload new PDF\n",
    "    st.markdown(\"---\")\n",
    "    st.subheader(\"📤 Upload New PDF\")\n",
    "    \n",
    "    uploaded_file = st.file_uploader(\"Choose PDF file\", type=['pdf'])\n",
    "    \n",
    "    if uploaded_file:\n",
    "        save_path = PATENTS_FOLDER / uploaded_file.name\n",
    "        with open(save_path, 'wb') as f:\n",
    "            f.write(uploaded_file.getbuffer())\n",
    "        st.success(f\"✅ Uploaded: {uploaded_file.name}\")\n",
    "        st.rerun()\n",
    "\n",
    "# ============================================================================\n",
    "# COLUMN 2: AI AGENT PANEL\n",
    "# ============================================================================\n",
    "\n",
    "with col2:\n",
    "    st.markdown('<div class=\"column-header\">🤖 AI AGENT</div>', unsafe_allow_html=True)\n",
    "    \n",
    "    if pdf_files and selected_file:\n",
    "        \n",
    "        # Keywords input\n",
    "        st.subheader(\"🔑 Enter Keywords/Phrases\")\n",
    "        \n",
    "        keywords_input = st.text_area(\n",
    "            \"Enter keywords (one per line):\",\n",
    "            height=150,\n",
    "            placeholder=\"Example:\\nPEPTIDE-BASED PROTACs\\npoly-D-arginine\\nwarhead discovery\"\n",
    "        )\n",
    "        \n",
    "        # Analyze button\n",
    "        if st.button(\"🚀 ANALYZE\", use_container_width=True, type=\"primary\"):\n",
    "            \n",
    "            if not keywords_input.strip():\n",
    "                st.error(\"❌ Please enter at least one keyword!\")\n",
    "            else:\n",
    "                # Parse keywords\n",
    "                search_items = [k.strip() for k in keywords_input.split('\\n') if k.strip()]\n",
    "                \n",
    "                with st.spinner('🔍 Analyzing PDF...'):\n",
    "                    # Search\n",
    "                    pdf_path = PATENTS_FOLDER / f\"{selected_file}.pdf\"\n",
    "                    results, match_percentage = search_pdf(pdf_path, search_items)\n",
    "                    \n",
    "                    # Create highlighted PDF\n",
    "                    highlighted_path = HIGHLIGHTED_FOLDER / f\"highlighted_{selected_file}.pdf\"\n",
    "                    total_highlights = highlight_pdf(pdf_path, highlighted_path, \n",
    "                                                    [k for k, v in results.items() if v['found']])\n",
    "                    \n",
    "                    # Store in session\n",
    "                    st.session_state.analyzed = True\n",
    "                    st.session_state.results = results\n",
    "                    st.session_state.match_percentage = match_percentage\n",
    "                    st.session_state.highlighted_pdf = highlighted_path\n",
    "                    st.session_state.total_highlights = total_highlights\n",
    "                    st.session_state.search_items = search_items\n",
    "        \n",
    "        # Show results\n",
    "        if st.session_state.analyzed:\n",
    "            st.markdown(\"---\")\n",
    "            st.subheader(\"📊 Analysis Results\")\n",
    "            \n",
    "            # Match percentage\n",
    "            match_pct = st.session_state.match_percentage\n",
    "            \n",
    "            if match_pct >= 80:\n",
    "                color = \"#28a745\"\n",
    "                emoji = \"🟢\"\n",
    "            elif match_pct >= 50:\n",
    "                color = \"#ffc107\"\n",
    "                emoji = \"🟡\"\n",
    "            else:\n",
    "                color = \"#dc3545\"\n",
    "                emoji = \"🔴\"\n",
    "            \n",
    "            st.markdown(f\"\"\"\n",
    "            <div class=\"metric-box\" style=\"border-left-color: {color};\">\n",
    "                <h2 style=\"color: {color}; margin: 0;\">{emoji} {match_pct:.1f}% Match</h2>\n",
    "                <p style=\"margin: 5px 0 0 0;\">\n",
    "                    Found {sum(1 for r in st.session_state.results.values() if r['found'])} / {len(st.session_state.search_items)} keywords\n",
    "                </p>\n",
    "            </div>\n",
    "            \"\"\", unsafe_allow_html=True)\n",
    "            \n",
    "            # Detailed results\n",
    "            st.markdown(\"**📍 Keyword Locations:**\")\n",
    "            \n",
    "            for item, data in st.session_state.results.items():\n",
    "                if data['found']:\n",
    "                    st.markdown(f\"\"\"\n",
    "                    <div class=\"success-box\">\n",
    "                        <b>✅ \"{item[:60]}{'...' if len(item) > 60 else ''}\"</b><br>\n",
    "                        📄 Pages: {', '.join(map(str, data['pages']))}<br>\n",
    "                        🔢 Occurrences: {data['count']}\n",
    "                    </div>\n",
    "                    \"\"\", unsafe_allow_html=True)\n",
    "                else:\n",
    "                    st.markdown(f\"\"\"\n",
    "                    <div class=\"warning-box\">\n",
    "                        <b>❌ \"{item[:60]}{'...' if len(item) > 60 else ''}\"</b><br>\n",
    "                        Not found in document\n",
    "                    </div>\n",
    "                    \"\"\", unsafe_allow_html=True)\n",
    "            \n",
    "            # Highlight info\n",
    "            st.info(f\"🎨 {st.session_state.total_highlights} areas highlighted in PDF\")\n",
    "    else:\n",
    "        st.info(\"👈 Select a PDF from the Source panel to begin\")\n",
    "\n",
    "# ============================================================================\n",
    "# COLUMN 3: PDF VIEWER PANEL\n",
    "# ============================================================================\n",
    "\n",
    "with col3:\n",
    "    st.markdown('<div class=\"column-header\">📄 PDF VIEWER</div>', unsafe_allow_html=True)\n",
    "    \n",
    "    if st.session_state.analyzed and st.session_state.highlighted_pdf:\n",
    "        \n",
    "        # Display highlighted PDF\n",
    "        pdf_path = st.session_state.highlighted_pdf\n",
    "        \n",
    "        if pdf_path.exists():\n",
    "            \n",
    "            # Show download button\n",
    "            with open(pdf_path, \"rb\") as f:\n",
    "                st.download_button(\n",
    "                    label=\"⬇️ Download Highlighted PDF\",\n",
    "                    data=f,\n",
    "                    file_name=pdf_path.name,\n",
    "                    mime=\"application/pdf\",\n",
    "                    use_container_width=True\n",
    "                )\n",
    "            \n",
    "            # Embed PDF viewer\n",
    "            with open(pdf_path, \"rb\") as f:\n",
    "                base64_pdf = base64.b64encode(f.read()).decode('utf-8')\n",
    "            \n",
    "            pdf_display = f'''\n",
    "                <iframe \n",
    "                    src=\"data:application/pdf;base64,{base64_pdf}\" \n",
    "                    width=\"100%\" \n",
    "                    height=\"800\" \n",
    "                    type=\"application/pdf\"\n",
    "                    style=\"border: 2px solid #ddd; border-radius: 5px;\">\n",
    "                </iframe>\n",
    "            '''\n",
    "            \n",
    "            st.markdown(pdf_display, unsafe_allow_html=True)\n",
    "            \n",
    "            st.success(\"✅ Yellow highlights show keyword matches\")\n",
    "        else:\n",
    "            st.error(\"Highlighted PDF not found\")\n",
    "    \n",
    "    elif pdf_files and selected_file:\n",
    "        # Show original PDF\n",
    "        pdf_path = PATENTS_FOLDER / f\"{selected_file}.pdf\"\n",
    "        \n",
    "        st.info(\"👈 Click ANALYZE to see highlighted version\")\n",
    "        \n",
    "        # Show original PDF\n",
    "        with open(pdf_path, \"rb\") as f:\n",
    "            base64_pdf = base64.b64encode(f.read()).decode('utf-8')\n",
    "        \n",
    "        pdf_display = f'''\n",
    "            <iframe \n",
    "                src=\"data:application/pdf;base64,{base64_pdf}\" \n",
    "                width=\"100%\" \n",
    "                height=\"800\" \n",
    "                type=\"application/pdf\"\n",
    "                style=\"border: 2px solid #ddd; border-radius: 5px;\">\n",
    "            </iframe>\n",
    "        '''\n",
    "        \n",
    "        st.markdown(pdf_display, unsafe_allow_html=True)\n",
    "    \n",
    "    else:\n",
    "        st.info(\"📄 PDF will appear here after analysis\")\n",
    "\n",
    "# Footer\n",
    "st.markdown(\"---\")\n",
    "st.markdown(\"\"\"\n",
    "<div style=\"text-align: center; color: #666; padding: 20px;\">\n",
    "    🔍 AI Patent Analyzer | Built with Streamlit | \n",
    "    <a href=\"https://github.com\" target=\"_blank\">Documentation</a>\n",
    "</div>\n",
    "\"\"\", unsafe_allow_html=True)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.19"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
